# Generated by Django 3.0 on 2019-12-11 09:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nationalite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='(no title)', max_length=50)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('director', models.CharField(default='...', max_length=30)),
                ('actor', models.CharField(blank=True, default='...', max_length=200, null=True)),
                ('epNumb', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('release', models.DateField(default='2000-01-01', verbose_name='Date de parution')),
                ('categorie', models.ManyToManyField(to='app.Categorie')),
                ('nationalite', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Nationalite')),
            ],
        ),
    ]
