# Generated by Django 3.0 on 2019-12-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_serie_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='categorie',
            new_name='categories',
        ),
    ]
