# Generated by Django 3.0 on 2019-12-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191219_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
