# Generated by Django 3.0.1 on 2019-12-24 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191223_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='seasonNumb',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
