# Generated by Django 3.0.1 on 2019-12-27 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191227_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
