# Generated by Django 3.0.1 on 2019-12-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='release',
            field=models.DateTimeField(default='2000-01-01'),
        ),
    ]
