# Generated by Django 3.0.1 on 2019-12-27 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191227_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
