# Generated by Django 3.0.1 on 2019-12-27 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_comment_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
